package MedievalTraderGame;

public enum STAGE {
    RULES,
    MAIN_MENU,
    TRAVEL_MENU,
    SELL_INVENTORY,
    BUY_VENDOR,
    HIRE_MERC,
    MANAGE_MERC,
    PICK_MERC,
    PICK_ITEM_TO_WEAR,
    ENTERPRISE_MENU,
    ON_THE_ARRIVAL_INFO,
    RUN_OR_FIGHT_MENU,
    GAME_OVER,
    FIGHT,
    QUIT,
    EXPEDITION_REPORT,
    CLOSE_GAME, EXPEDITION_MENU
}
